<div class="container">
    <div class="row">
        <div class="col-xs-12 col-md-8">
                 <h2> Admin test page</h2>

                        <form action="<?= $action ?>" method="POST" >
                            <div class="form-group upDownSpace">

                                <label>Post Title</label>
                                <input type="text" name="postTitle" value="<?= $postTitle ?? ' ' ?>" class="form-control" />

                            <br /><br />

                               <label>Category</label>
                                <input type="text" name="postCategory" value="<?= $category ??  ''?>" class="form-control"/>

                            <br /><br />

                                <label> Post Message</label><br />
                                <textarea name="postMessage" class="form-control" rows="7"><?= $message ?? ''?></textarea><br /><br />

                                <input type="submit"  name="submit" value="Insert Post" class="btn btn-default"/>
                            </div>
                        </form>

        </div>
    </div>
</div>
