<div class="container">
    <div class="row">
        <div class="col-xs-12 col-md-8">
            <div class="panel panel-default panelSpace text-center">
                <h1><strong>404: Puslapis nerastas</strong></h1>
                <h3> Patikrinkyte ivesta adresa dar karta</h3>
                <a href="?page=home">Grižti į pradžią</a>
            </div>

        </div>
    </div>

</div>










