<div class="container">
    <div class="row">
        <div class="col-xs-12 col-md-8">
            <div class="panel panel-default panelSpace">
                <h1> About Me</h1>
                <p><img src="img/as.JPG"  height="100px" width="150px" alt="Andrej nuotrauka"/> Esu vardu Andrej. Šiuo metu dirbu taip pat esu codeacademy PHP kursu pradedantiesiems studentas. </p>
            </div>

        </div>

    </div>

</div>
