<footer>
    <div class="panel-footer footerStyle text-center">
        <div class="row">
            <div class="col-xs-6 col-md-4">
                <div class="socialButtonSpace">
                    <!--Facebook-->
                    <a href="https://www.facebook.com/" target="_blank"><button type="button" class="btn btn-fb"><i class="fa fa-facebook left"></i> Facebook</button></a>
                    <!--Twitter-->
                    <a href="https://twitter.com/" target="_blank"><button type="button" class="btn btn-tw"><i class="fa fa-twitter left"></i> Twitter</button></a>
                    <!--Google plus-->
                    <a href="https://www.google.lt" target="_blank"><button type="button" class="btn btn-gplus"><i class="fa fa-google-plus left"></i> Google +</button></a>
                    <!--Linkedin-->
                    <a href="https://www.linkedin.com/" target="_blank"><button type="button" class="btn btn-li"><i class="fa fa-linkedin left"></i> Linkedin</button></a>
                    <!--Instagram-->
                    <a href="https://www.instagram.com/" target="_blank"><button type="button" class="btn btn-ins"><i class="fa fa-instagram left"></i> Instagram</button></a>
                </div>
            </div>

            <div class="col-xs-6 col-md-4 " style="padding-top: 35px">
                <ul class="list-group footerMeniu" style="list-style: none;">
                    <li><a href="?page=home">Home <span class="sr-only">(current)</span></a></li>
                    <li><a href="?page=page/aboutus">About Us</a></li>
                    <li><a href="?page=page/contact">Contact</a></li>
                </ul>
            </div>

            <div class="col-xs-6 col-md-4" style="padding-top: 35px">

                <p>Copyright <span class="glyphicon glyphicon-copyright-mark" aria-hidden="true"></span> 2018 </p>
            </div>
        </div>

    </div>

</footer>

</body>
</html>