<div class="col-xs-6 col-md-4 sidebarRight text-center">
    <div class=" panel panel-default listPanel">
        <div  style="margin-top: 30px; padding-bottom: 30px;">

            <?php if (isset($_SESSION['admin'])) : ?>
                <p>Prisijunges dabar: <strong><?= isLoggedIn() ?></strong>
                <a href="?page=logout">Atsijungti</a></p></p>
            <?php endif;?>
            <?php if (!isset($_SESSION['admin'])) :?>
                <form action="?page=admin/login" class="form-inline" method="POST">
                <div class="form-group">
                <label class="sr-only formTextColor" >User name</label>
                <input type="text" name="username" class="form-control"  placeholder="User name"><br /><br />

                <label class="sr-only formTextColor" >Password</label>
                <input type="password" name="password" class="form-control"  placeholder="Password"><br /><br />
                <button type="submit" name="submit" class="btn btn-default">Sign in</button>
                </div>
                </form>
            <?php endif; ?>
        </div>
    </div>
</div>
